routes/web.php
<?php
Route::get('/','MainController@index');

Route :: get('/home', 'MainController@index');

Route :: get('/contact',function() {
    return view('layouts/contact');
});

Route :: get('/services',function() {
    return view('layouts/services');
});
Route :: get('/team',function() {
    return view('layouts/team');
});
Route :: get('/blog',function() {
    return view('layouts/blog');
});

Route::get('admin/users', function () {
    return view('admin/users');
});

Auth::routes();

Route::get('/layouts/home', 'HomeController@index')->name('/home');
Route::post('/users/store', 'UserController@store');


Route::resource('admin/users', 'UserController');

Route::get('users', 'UserController@index')->name('admin/users')
    ->middleware('auth');

Route::get('/dashboard', function () {
    return view('admin/mainpage');
});

Route::resource('/detail','PostController');
Route::resource('/aboutus','AboutusController');
Route::resource('/post','PostController');
Route::resource('/gallery','GalleryController');
Route::resource('/categories','CategoryController');
Route::resource('/create','ImageController');
Route::resource('/event','EventController');
Route::resource('/slider','SliderimageController');

//
//Route::get('/detail/{description}', function ($id) {
//    return view('admin/detail'.$id);
//});

resources/views/layouts/aboutus.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Saparc Agro Website</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Hind&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Grand+Hotel&display=swap" rel="stylesheet">

    <style>

        .navbar-nav .nav-item{

            margin-right: 30px;
            font-family: 'Hind', sans-serif;
            font-weight: bold;
        }
        .navbar-nav a:hover{
            background-color: #9cc900;
        }


        .page_top_wrap {
            background: #313a42;
            overflow: hidden;
            height: 75px;
            margin-bottom: 30px;
        }
        .page_top_wrap .page_title{
            font-size: 25px;
            padding-left: 90px;
            text-transform: none;
            width: 50%;
            color: white;
            background-color: #313a42;
            margin-top: 20px;
        }
        .page_top_wrap.page_top_title .breadcrumbs {
            width: 50%;
            float: right;
            margin-top: 10px;
            padding-right: 50px;
            /*line-height: normal;*/
            text-align: right;
            font-size: 15px;
            color: #ffffff;
        }
        .page_top_breadcrumbs .breadcrumbs_item{
            color: darkgray;
        }
        .page_top_breadcrumbs .breadcrumbs_item:hover{
            color: #ffffff;
            text-decoration: none;
        }
        .page_top_wrap .breadcrumbs .breadcrumbs_delimiter {
            vertical-align: top;
            top: 0;
        }
        .page_top_wrap .breadcrumbs .breadcrumbs_delimiter {
            display: inline-block;
            position: relative;
            top: 4px;
            color: #a6ccc0;
            font-size: 16px;
            margin: 0 10px;
        }

        img{
            border-style:none;
        }
        p{
            margin-top:0;
            margin-bottom: 0;
        }
        .footer-color {
            background-color: #313a42;
            padding: 20px !important;
            margin: 0px 0px !important;
            max-width: 100%;
        }
        .ftco-heading-2 {
            color: white;
            font-size: 20px;
            font-family: sans-serif;
            font-weight: 400;
        }
        .ftco-footer-widget {
            /*text-align: center;*/
        }
        a{
            color:white;
        }
        .container{
            margin-top: 30px;
        }
        .sc_line {
            color: #9cc900;
            height: 4px;
            margin: 12px;
            border: 2px;
            margin: auto;
            width: 50px;
            margin-top: 0px;
            margin-top: 20px;
        }


    </style>
</head>
<body>
<!--- Navigation -->
@include('layouts.navbar')

<div class="body-wrap">
    <div class="page_top_wrap page_top_title page_top_breadcrumbs">
        <div class="content_wrap">
            <div class="breadcrumbs">
                <a class="breadcrumbs_item home" href=" ">Home</a>
                <span class="breadcrumbs_delimiter"><i class="fa fa-angle-right" aria-hidden="true"></i></span>
                <span class="current">About Us</span>
            </div>
            <h3 class="page_title" >About Us</h3>
        </div>
    </div>
</div>

<div class="container-body">
    <section class="my-3">
        <div class="py-2">
            @foreach($about as $data)
            <h2 class="text-center"> {{$data->title}}</h2>
            <div class="sc_line" style="border-top-style:double;"></div>
                @endforeach
        </div>
        <p style="margin-left: 30px;margin-right: 30px;text-align: justify;">{{$data->description}}</p>

    </section>
</div>


<br>
@include('layouts.footer')



</body>
</html>

resources/views/layouts/advertisement.blade.php
<html>
<head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="style.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
</head>





<body>
<nav class=" fixed-nav-bar navbar navbar-expand-lg navbar-dark bg-color fixed-top">
    <a class="navbar-brand" href="{{url('/home')}}"><img src="image/logo-white.png "></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item ">
                <a class="nav-link" href="{{url('/home')}}"> Home </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url('/contact')}}">Contact </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url('/team')}}">Team</a>
            </li><li class="nav-item">
                <a class="nav-link" href="{{url('/aboutus')}}">About Us</a>

            </li><li class="nav-item">
                <a class="nav-link" href="{{url('/services')}}">Services</a>
            </li>
        </ul>

    </div>
</nav>
<div class = "py-5">
    <h2 class = "text-center">Advertisement</h2>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6 col-lg-6 col-12 ">
            <img src="image/eight.jpg " class="img-fluid">
        </div>
        <div class="col-lg-6 col-lg-6 col-12 ">
        </div>
    </div>
</div>







@include('layouts.footer')
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>

    <style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: Arial;
            font-size: 17px;
        }

        .container {
            position: relative;
            max-width:100% !important;
            padding: 0px !important;
        }

        .container img {vertical-align: middle;}
    </style>
</head>
<body>

<div class ="droupdown-menu droupdown-menu-right " aria-labelledby ="">
<div class="container" >
    <img src="{{asset('image/ag1.jpg.jfif')}} " height="100%" width="100% ">

<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest

                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>



    <div>
            @yield('content')
    </div>
</div>

</body>
</html>

resources/views/layouts/blog.blade.php
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Saparc Agro Website</title>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="bootstrap-4.1.3-dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Grand+Hotel&display=swap" rel="stylesheet">
{{--    <link rel="stylesheet" type="text/css" href="{{ asset("style.css")}}">--}}
    <style>
        .navbar-nav .nav-item{

            margin-right: 30px;
            font-family: 'Hind', sans-serif;
            font-weight: bold;
        }
        .navbar-nav a:hover{
            background-color: #9cc900;
        }

        .page_top_wrap {
            background: #313a42;
            overflow: hidden;
            height: 75px;
            margin-bottom: 30px;
        }
        .page_top_wrap .page_title{
            font-size: 25px;
            padding-left: 90px;
            text-transform: none;
            width: 50%;
            color: white;
            background-color: #313a42;
            margin-top: 20px;
        }
        .page_top_wrap.page_top_title .breadcrumbs {
            width: 50%;
            float: right;
            margin-top: 10px;
            padding-right: 50px;
            /*line-height: normal;*/
            text-align: right;
            font-size: 15px;
            color: #ffffff;
        }
        .page_top_breadcrumbs .breadcrumbs_item{
            color: darkgray;
        }
        .page_top_breadcrumbs .breadcrumbs_item:hover{
            color: #ffffff;
            text-decoration: none;
        }
        .page_top_wrap .breadcrumbs .breadcrumbs_delimiter {
            vertical-align: top;
            top: 0;
        }
        .page_top_wrap .breadcrumbs .breadcrumbs_delimiter {
            display: inline-block;
            position: relative;
            top: 4px;
            color: #a6ccc0;
            font-size: 16px;
            margin: 0 10px;
        }
        img{
            border-style:none;
        }
        p{
            margin-top:0;
            margin-bottom: 0;
        }
        .footer-color {
            background-color: #313a42;
            padding: 20px !important;
            margin: 0px 0px !important;
            max-width: 100%;
        }
        .ftco-heading-2 {
            color: white;
            font-size: 20px;
            font-family: sans-serif;
            font-weight: 400;
        }
        .ftco-footer-widget {
            /*text-align: center;*/
        }
        a{
            color:white;
        }
        .container{
            margin-top: 30px;
        }
    </style>
</head>
<body>
@include('layouts.navbar')

<div class="body-wrap">
    <div class="page_top_wrap page_top_title page_top_breadcrumbs">
        <div class="content_wrap">
            <div class="breadcrumbs">
                <a class="breadcrumbs_item home" href=" ">Home</a>
                <span class="breadcrumbs_delimiter"><i class="fa fa-angle-right" aria-hidden="true"></i></span>
                <span class="current">Blog</span>
            </div>
            <h3 class="page_title" >Blog</h3>
        </div>
    </div>
</div>


@include('layouts.footer')
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="ftco-footer ftco-section footer-color " style="padding-top:50px;">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-4">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2"><b>STAY CONNECTED</b></h2>
                    <p><i class="fa fa-map-marker" aria-hidden="true" style="color: white;"></i>
                        <small style="color: papayawhip; margin: 10px;"> Mid Baneshwor , Prabachan Marg, Kathmandu </small>  </p>
                    <p> <i class="fa fa-phone" aria-hidden="true" style="color: white;"></i> <small style="color: papayawhip; margin: 10px;">
                            9814241960 </small> </p>
                    <p> <i class="fa fa-envelope" aria-hidden="true" style="color:white;"></i><small style="color: papayawhip; margin: 10px;"> kandelsujata333@gmail.com </small></p>
                </div>
                <i class="fa fa-facebook" style="color:darkblue;margin-right: 10px;font-size: 20px;"></i>
                <i class="fa fa-instagram" style="color:  #e60571;margin-right: 10px;font-size: 20px;"></i>
                <i class="fa fa-twitter"style="color: #00acee;font-size: 20px;"></i>
            </div>
            <div class="col-md-4 no-padding-bottom col-sn-4 col-xs-12" ;>
                <h2 class="ftco-heading-2"><b>ABOUT US</b></h2>
                <p> <small style="color: papayawhip">Six Sigma is "A Complete Guide to Technology" and the ultimate portal to get information, news,
                        reviews, price, comparison of different products and connecting the buyer with the nearest
                        store. </small></p>
            </div>
            <div class="col-md-4">
                <div class="ftco-footer-widget mb-4 md-4">
                    <h2 class="ftco-heading-2"><b> NAVIGATE </b></h2>
                    <ul class="list-unstyled" style="font-size:12px; line-height: 20px;">

                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Privacy </a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Terms & Conditions</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Contact Us</a></li>

                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-center">
            <p class="p-3 bg-dark text-white">
                © sixsigma.com -
                <script type="text/javascript">
                    document.write(new Date().getFullYear());
                </script>
                All rights reserved. &nbsp;&nbsp;&nbsp
            </p>
        </div>
    </div>
</footer>

resources/views/layouts/home.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> Saparc Agro Website</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.css" rel="stylesheet" >
    <link href="https://fonts.googleapis.com/css?family=Hind&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Grand+Hotel&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{{ asset("style.css")}}">


</head>
<body>
<!--- Navigation -->

@include('layouts.navbar')
    <div id="myCarousel" class="carousel slide" data-ride="carousel">

        <ol class="carousel-indicators">
            <li data-target="#slides" data-slide-to="0" class="active"></li>
            <li data-target="#slides" data-slide-to="1"></li>
            <li data-target="#slides" data-slide-to="2"></li>
        </ol>

        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{{asset('image/one.jpg')}}" style="width: 100%; height: 500px;">
                <div class="carousel-caption">
                    <h1>Create</h1>
                    <p class="lead" >This text is super engaging and makes you want to click the button.</p>
                    <a href="#" class="btn btn-lg btn-primary">Learn More </a>
                </div>
            </div>
            <div class="carousel-item ">
                <img src="{{asset('image/two.jpg')}}" style="width: 100%; height: 500px;">
                <div class="carousel-caption">
                    <h1>Check Out</h1>
                    <p class="lead"  >This text is super engaging and makes you want to click the button.</p>
                    <a href="#" class="btn btn-lg btn-primary">Learn More</a>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{{asset('image/three.jpg')}}" style="width: 100%; height: 500px;">
                <div class="carousel-caption">
                    <h1>Check Moose</h1>
                    <p class="lead">This text is super engaging and makes you want to click the button.</p>
                    <a href="#" class="btn btn-lg btn-primary">Learn More</a>
                </div>
            </div>
            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

    </div>

    <div class="wpb_wrapper">
        <div class="sc_section animated fadeInDown normal" data-animation="animated fadeInDown normal">
            <h3 class="sc_title sc_title_regular sc_align_center title_with_b" style=
            "margin-top:30px; text-align:center;">

                <b> <span class="bold-text-green">20 years </span></b>
                of making changes

            </h3>
        </div>
    </div>
    <div class="sc_line" style="border-top-style:double;"></div>

    <h4 class="content" style="margin-top:.44em;">
        <p style="font-size: 20px; text-align:center; margin-bottom: 30px;"> This is my homepage </p>
    </h4>



<div data-vc-full-width="true" data-vc-full-width-init="true" data-vc-stretch-content="true" class="vc_row wpb_row vc_row-fluid vc_row-no-padding" style="position: relative;  box-sizing: border-box; width:100%;">
    <div class="wpb_column vc_column_container vc_col-sm-12">
        <div class="vc_column-inner">
            <div class="wpb_wrapper">
                <div class="sc_parallax bg_tint_light" data-parallax-speed="-0.1" data-parallax-x-pos="50%" data-parallax-y-pos="50%">
                    <div class="sc_parallax_content" style="background-image: url(&quot;http://greenrescue.ancorathemes.com/wp-content/uploads/2015/02/bg3.jpg&quot;); background-position: 50% -1px;">
                        <div class="sc_section" style="padding: 5em 0;">
                            <h2 class="sc_title sc_title_regular sc_align_center" style="color:#fff;text-align:center; font-family: 'Hind'; font-weight: bold; font-size: 40px; margin-top: -20px;">{{ $event->event_title }}</h2>
                            <div class="sc_line sc_line_style_double" style="border-top-style:double;border-top-color:#9cc900;"></div>
                            <div class="sc_section" style="color:#ffffff;">
                                <div class="wpb_text_column wpb_content_element  text-phone">
                                    <div class="wpb_wrapper">
                                        <p style="text-align: center; font-family: 'Hind', sans-serif;font-size: 15px; margin-top: 15px;">{{ ($event->event_description) }}</p>
                                    </div>
                                </div>
                                <h5 class="sc_title sc_title_regular sc_align_center title_with_b" style="margin-bottom:2em;text-align:center;color: #9cc900; font-family: 'Grand Hotel';  font-weight: bold;">{{ $event->starting_date }}</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{{--    <div class="content-wrapper">--}}
{{--        <img src="{{asset('image/climate.jpg')}}">--}}

{{--        <div class="text-wrapper1">--}}
{{--            <h1 style="font-size: 40px;"><b>{{ $event->event_title }}</b></h1>--}}
{{--            <div class="sc_line2 " style="border-top-style:double;">--}}
{{--            </div>--}}
{{--            <div>--}}
{{--                <p style="text-align: center; font-family: Hind; color: white; margin-top: -10px;  font-size: 20px;"> {{ ($event->event_description) }}</p>--}}
{{--            </div>--}}
{{--            <h3 class="date" style="margin-top:10px;text-align:center; font-family:'Grand Hotel', cursive;color:#9cc900"><b>{{ $event->starting_date }}</b></h3>--}}
{{--            <div class="container block-countdown ">--}}
{{--                <div id="countdown"></div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}

    <br/><br/>





        <p style="font-size:30px; text-align:center; margin-bottom: 30px;">Our Projects</p>
        <div class="sc_line1" style="border-top-style:double; margin-bottom: 30px;"></div>

        <div class="page-content page-container" id="page-content">
            <div class="padding">
                <div class="row container-fluid">
                    <div class="col-lg-12 grid-margin stretch-card">
                        <div class="card">
                            <div class="card-body">
                                <div class="owl-carousel">
                                    @foreach($data as $content)
                                        <div class="item">
                                          <a href="{{route('detail.show',$content->id)}}">
                                              <img src="{{asset ('uploads/photos/' . $content->image)}}" alt="image" >
                                              <h3><a href="{{route('detail.show',$content->id)}}">{{$content->title}}</a></h3>
                                              <h6 class="small text-wide p-b-2 "> {{($content->created_at)}}</h6>
                                              <div class="text-block">
                                                  <h4><a href="{{route('detail.show',$content->id)}}">{{$content->title}}</a></h4>
                                                  <h6 class="small text-wide p-b-2 "> {{($content->created_at)->format('Y-m-d')}}</h6>
                                              </div>
                                          </a>
                                            <h3><a href="{{route('detail.show',$content->id)}}">{{$content->title}}</a></h3>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <br/>

    <div class="container-fluid padding">
        <div class="row welcome text-center">
            <div class="col-12">
                <p style="font-size:30px; text-align:center;">Meet the team</p>
            </div>
            <div class="sc_line"style="border-top-style:double;">

            <hr>
            <br>
        </div>
    </div>

    <br>
    <br>
    <div class="container-fluid padding">
        <div class="row padding">

            <div class="col-md-4">

                <div class="card">
                    <img class="card-img-top" src="image/palle.jpg">
                    <div class="card-body">
                        <h6 class="card-title"> Pallavi Bhattarai </h6>
                        <p class="card-text"> Pallavi is is an Internet enterpreneur with almost 2 years of experience. </p>

                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img class="card-img-top" src="image/suju.JPG">
                    <div class="card-body">
                        <h6 class="card-title"> Sujata Kandel </h6>
                        <p class="card-text"> Sujata is a designer with almost 2 years of digital design experience. </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card" >
                    <img class="card-img-top" src="image/shilpa.JPG">
                    <div class="card-body">
                        <h6 class="card-title"> Sheelpa Sapkota</h6>
                        <p class="card-text"> Sheelpa is a web developer with 5 years of web development experience. </p>


                    </div>
                </div>
            </div>
        </div>

        </div>
    </div>
<br>

@include('layouts.footer')




    <!---Script Source Files--->
    <script src="{{ asset("js/jquery-3.3.1.min.js") }}"></script>
    <script src="bootstrap-4.1.3-dist/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.js"></script>
    <!---End of Script Source Files--->
    <script>
        $(document).ready(function() {

            $(".owl-carousel").owlCarousel({

                autoPlay: 3000,
                items : 3,
                itemsDesktop : [1199,3],
                itemsDesktopSmall : [979,3],
                center: true,
                nav:true,
                loop:true,
                responsive: {
                    600: {
                        items: 3
                    }
                }

            });

        });

    </script>

</body>
</html>

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top" style="height: 90px;">
    <div class="container-fluid">
        <a class="nabvar-brand" href="{{url('/home')}}"><img src="{{asset('image/green.jpg')}}"
                                                             height="45px" style="padding-left: 60px;">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active ">
                    <a class="nav-link" href="{{url('/home')}}"> Home</a></li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{url('/contact')}}"> Contact</a></li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{url('/aboutus')}}"> About Us</a></li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{url('/services')}}"> Services</a></li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{url('/blog')}}"> Blog</a></li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{url('/gallery')}}"> Gallery</a></li>
            </ul>
        </div>
    </div>
</nav>